global:
  resolve_timeout: 5m

route:
  receiver: lark
  group_by: [alertname, severity]
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 4h

receivers:
  - name: lark
    webhook_configs:
      - url: http://lark-webhook:8080/webhook
        send_resolved: true
