-- =============================================================================
-- GISO 注册表元库 — 与 GIDO / DataEase 共用 RDS，独立库 giso
-- =============================================================================
--
-- 1. 以 RDS 主账号连接 postgres 库，执行「建库」
-- 2. 连接 giso 库，执行 tools/registry/bootstrap_schema.sql（授权应用账号）
-- 3. 部署 Gateway：启动时自动跑 V1/V2/V3 迁移；库为空时从 /app/schema 种子导入
-- 4. 可选：python3 tools/registry/import_yaml.py
--
-- Doppler（与 DataEase 同 RDS 实例）：
--   INFRA_GISO_DB_SERVICE_URL / USER / PASSWORD
--   → K8s GISO_DB_URL / GISO_DB_USER / GISO_DB_PASSWORD
--
-- =============================================================================

-- 步骤 1：主账号在 postgres 库执行
-- CREATE DATABASE giso;
-- CREATE USER "giso-user" WITH PASSWORD 'CHANGE_ME';
-- GRANT CONNECT ON DATABASE giso TO "giso-user";

-- 步骤 2：主账号在 giso 库执行 bootstrap_schema.sql（见同目录）
